{-
Problem 002:

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed
one million.
-}

fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
main = print $ sum [x | x <- takeWhile (<= 1000000) fibs, even x]
